version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/game-test
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: |
            pwd
            ls -la
            aws s3 sync ./public s3://game-test-1535/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
